#!/bin/bash
# remove-vm
# Paul Stivers
# last updated: 2013-09-25

usage="usage: $0 <vm hostname>" 
example="example: $0 vm01" 

vm_hostname=$1
help_state=$1

if [ "$help_state" = help ]; then
    echo 
    echo "$usage"
    echo "$example"
    echo
    exit 0
fi

# if vm hostname is null, notify the user 
if [ "$vm_hostname" = "" ]; then
    echo
    echo "enter the vm hostname on the command line"
    echo "$usage"
    echo "$example"
    echo 
    exit 1
fi

# undefine the vm
sudo ls > /dev/null
echo
echo "*** virsh destroying $vm_hostname if it exists"
echo "destroy $vm_hostname" | virsh
echo
echo "*** virsh undefining $vm_hostname if it exists"
echo "undefine $vm_hostname" | virsh
echo
echo "removing file /etc/libvirt/qemu/$vm_hostname"
if [ -d /etc/libvirt/qemu/$vm_hostname ]; then
    sudo rm /etc/libvirt/qemu/$vm_hostname
fi
echo "removing directory /var/lib/libvirt/images/$vm_hostname"
if [ -d /var/lib/libvirt/images/$vm_hostname ]; then
    sudo rm -r /var/lib/libvirt/images/$vm_hostname
fi
echo

exit 0

